"""empty message

Revision ID: 022c3b66e195
Revises: 2382fb779744
Create Date: 2021-06-10 13:34:26.173754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022c3b66e195'
down_revision = '2382fb779744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_status', 'time_created')
    op.drop_column('request_status', 'date_created')
    op.drop_column('request_status', 'user_id')
    op.add_column('request', sa.Column('institution', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
