"""empty message

Revision ID: 26f0c3bd75f3
Revises: cff26216565f
Create Date: 2021-06-18 11:30:48.763425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f0c3bd75f3'
down_revision = 'cff26216565f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('message',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('message', sa.String(), nullable=True),
    # sa.Column('date_created', sa.Date(), nullable=True),
    # sa.Column('time_created', sa.String(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.alter_column('request', 'time_created',
    #            existing_type=sa.TIME(),
    #            nullable=False)
    # op.drop_column('request', 'institution')
    # op.create_unique_constraint(None, 'request_status', ['student'])
    # op.create_unique_constraint(None, 'request_status', ['token_id'])
    # op.drop_column('request_status', 'confirmed')
    op.add_column('message', sa.Column('user_id', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_status', sa.Column('confirmed', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'request_status', type_='unique')
    op.drop_constraint(None, 'request_status', type_='unique')
    op.add_column('request', sa.Column('institution', sa.VARCHAR(), nullable=True))
    op.alter_column('request', 'time_created',
               existing_type=sa.TIME(),
               nullable=True)
    op.drop_table('message')
    # ### end Alembic commands ###
