"""empty message

Revision ID: 2e03de80e62f
Revises: ba5defab7f1c
Create Date: 2021-06-09 13:48:08.829981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e03de80e62f'
down_revision = 'ba5defab7f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('request_status',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('token_id', sa.String(), nullable=False),
    # sa.Column('confirmed', sa.Boolean(), nullable=True),
    # sa.Column('status', sa.String(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.drop_table('request_statuses')
    # op.alter_column('request', 'time_created',
    #            existing_type=sa.TIME(),
    #            nullable=True)
    # op.drop_column('request', 'institution')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('request', 'time_created',
    #            existing_type=sa.TIME(),
    #            nullable=True)
    # op.create_table('request_statuses',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('student_id', sa.VARCHAR(), nullable=False),
    # sa.Column('status', sa.VARCHAR(), nullable=False),
    # sa.Column('expiration_date', sa.DATE(), nullable=True),
    # sa.Column('confirmed', sa.BOOLEAN(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.drop_table('request_status')
    # ### end Alembic commands ###
    pass
