"""empty message

Revision ID: 5b1b6136f77b
Revises: 6e5cd70b2b8b
Create Date: 2021-07-21 00:42:43.287422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1b6136f77b'
down_revision = '6e5cd70b2b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'students', ['id'])
    op.drop_column('students', 'rec_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('rec_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'id')
    # ### end Alembic commands ###
