"""empty message

Revision ID: 6e5cd70b2b8b
Revises: ecb7c9fc5c19
Create Date: 2021-07-19 11:52:09.041658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5cd70b2b8b'
down_revision = 'ecb7c9fc5c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('reg_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('surname', sa.String(length=80), nullable=True),
    sa.Column('programme', sa.String(length=80), nullable=True),
    sa.Column('degree_class', sa.String(length=80), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('rec_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('rec_id'),
    sa.UniqueConstraint('surname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
