"""empty message

Revision ID: 9ce229977490
Revises: 
Create Date: 2021-05-27 14:13:15.813186

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9ce229977490'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('request', sa.Column('institution_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('requests',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('user_id', sa.VARCHAR(), nullable=False),
                    sa.Column('student_id', sa.VARCHAR(), nullable=False),
                    sa.Column('date_created', sa.DATE(), nullable=True),
                    sa.Column('verified', sa.BOOLEAN(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
