"""empty message

Revision ID: ba5defab7f1c
Revises: 9ce229977490
Create Date: 2021-05-28 10:45:43.357426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5defab7f1c'
down_revision = '9ce229977490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('institution', sa.VARCHAR(), nullable=True))
    op.alter_column('request', 'time_created',
               existing_type=sa.TIME(),
               nullable=True)
    op.alter_column('request', 'institution_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(), nullable=False),
    sa.Column('date_created', sa.DATE(), nullable=True),
    sa.Column('verified', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
