"""empty message

Revision ID: c7f73e603b0e
Revises: 2e03de80e62f
Create Date: 2021-06-09 13:50:30.955498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f73e603b0e'
down_revision = '2e03de80e62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('institution', sa.VARCHAR(), nullable=True))
    op.alter_column('request', 'time_created',
               existing_type=sa.TIME(),
               nullable=True)
    # ### end Alembic commands ###
