"""empty message

Revision ID: cf008cb5858c
Revises: 022c3b66e195
Create Date: 2021-06-10 13:36:22.993690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf008cb5858c'
down_revision = '022c3b66e195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('institution', sa.VARCHAR(), nullable=True))
    # op.alter_column('request', 'time_created',
    #            existing_type=sa.TIME(),
    #            nullable=True)
    # ### end Alembic commands ###
