"""empty message

Revision ID: cff26216565f
Revises: 0cf53dbcd755
Create Date: 2021-06-11 00:22:09.208277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff26216565f'
down_revision = '0cf53dbcd755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_status', sa.Column('confirmed', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'request_status', type_='unique')
    op.drop_constraint(None, 'request_status', type_='unique')
    op.drop_column('request_status', 'student')
    op.add_column('request', sa.Column('institution', sa.VARCHAR(), nullable=True))
    op.alter_column('request', 'time_created',
               existing_type=sa.TIME(),
               nullable=True)
    # ### end Alembic commands ###
