"""empty message

Revision ID: e2b2c29f5edb
Revises: c7f73e603b0e
Create Date: 2021-06-10 12:13:53.221693

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e2b2c29f5edb'
down_revision = 'c7f73e603b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_status', 'time_created')
    op.drop_column('request_status', 'date_created')
    op.drop_column('request_status', 'user_id')
    op.add_column('request', sa.Column('institution', sa.VARCHAR(), nullable=True))
    op.alter_column('request', 'time_created',
                    existing_type=sa.TIME(),
                    nullable=True)
    # ### end Alembic commands ###
