"""empty message

Revision ID: ecb7c9fc5c19
Revises: 
Create Date: 2021-07-19 10:10:37.302182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb7c9fc5c19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('time_created', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('time_created', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password1', sa.String(length=100), nullable=True),
    sa.Column('password2', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('last_request_view_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('request_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('student', sa.String(), nullable=True),
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('time_created', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student'),
    sa.UniqueConstraint('token_id')
    )
    op.create_index(op.f('ix_request_status_timestamp'), 'request_status', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_status_timestamp'), table_name='request_status')
    op.drop_table('request_status')
    op.drop_table('user')
    op.drop_table('request')
    op.drop_table('message')
    # ### end Alembic commands ###
